ARG ubuntu_base=fczuardi/bionic

FROM ${ubuntu_base} AS ubuntu
MAINTAINER Fabricio Zuardi <fabricio@fabricio.org>
ARG ubuntu_base
RUN echo Ubuntu base is: $ubuntu_base
RUN echo Docker tag is: $DOCKER_TAG


