#!/bin/sh
env
if [ "$DOCKER_TAG" = "latest" ]; then
  docker build -f $DOCKERFILE_PATH -t $IMAGE_NAME .
else
  NODE_VERSION=12.10.0
  docker build \
    --build-arg DOCKER_TAG=$DOCKER_TAG \
    --build-arg NODE_VERSION=$NODE_VERSION \
    -f $DOCKERFILE_PATH \
    -t $IMAGE_NAME .
fi

